apps/blog/urls.py
from django.urls import path

from apps.blog.blog_entry_views import BlogEntriesView, BlogEntryView, CreateBlogEntryView, DeleteBlogEntryView

app_name = 'blog'
urlpatterns = [
    path('', BlogEntriesView.as_view(), name='entries'),
    path('<int:pk>', BlogEntryView.as_view(), name='entry_detail'),
    path('<int:pk>/delete', DeleteBlogEntryView.as_view(), name='delete_entry'),
    path('new', CreateBlogEntryView.as_view(), name='new_entry'),
]

apps/pika_app/urls.py
from django.urls import path

from . import index

app_name = 'pika_app'
urlpatterns = [
    path('', index.IndexView.as_view(), name='index'),
]

pika/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.pika_app.urls')),
    path('blog/', include('apps.blog.urls')),
]

apps/blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{ entry.title }} | Pika blog{% endblock %}
{% block heading %}{{ entry.title }}{% endblock %}
{% block content %}
    <span>{{ entry.author }}</span>
    <p>{{ entry.body }}</p>

    <a href="{% url 'blog:entries' %}">Back to blog entries</a>
{% endblock %}

apps/blog/templates/blog/list.html
{% extends 'base.html' %}

{% block title %}Pika blog{% endblock %}
{% block heading %}Pika blog{% endblock %}
{% block content %}
    <a href="{% url 'blog:new_entry' %}">New blog entry</a>


    {% if blog_entries %}
        <ul>
            {% for entry in blog_entries %}
                <li>
                    <a href="{% url 'blog:entry_detail' entry.id %}">{{ entry.title }}</a>
                    <form action="{% url 'blog:delete_entry' entry.id %}" method="post" class="inline">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                    </form>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No entries are available.</p>
    {% endif %}
{% endblock %}

apps/blog/templates/blog/new.html
{% extends 'base.html' %}

{% block title %}Pika blog{% endblock %}
{% block heading %}Create entry{% endblock %}
{% block content %}
    <form action="{% url 'blog:entries' %}" method="post">
        {% csrf_token %}
        <label>
            Title
            <input type="text" name="title">
        </label>
        <label>
            Author
            <input type="text" name="author">
        </label>
        <label>
            Body
            <textarea name="body"></textarea>
        </label>

        <input type="submit" value="Create">
    </form>
{% endblock %}

apps/pika_app/templates/index.html
{% extends 'base.html' %}

{% block title %}Pika home{% endblock %}
{% block heading %}Pika home{% endblock %}
{% block content %}Oh, hi!{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>{% block title %}Pika{% endblock %}</title>
</head>

<body>
<header>
    <h1>{% block heading %}{% endblock %}</h1>
</header>
<main>{% block content %}{% endblock %}</main>
</body>
</html>